language: objective-c
cache: cocoapods
osx_image: xcode8.2.1
before_install:
  - gem install xcov --no-ri --no-rdoc --no-document
  - gem update fastlane --no-ri --no-rdoc --no-document
script:
  - fastlane test