# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.10.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      platform: ios
      scheme: "booklending",
      slack_url: ENV["SLACK_URL"],
      output_style: "rspec",
      code_coverage: true
    )

    xcov(
      workspace: "booklending.xcworkspace",
      scheme: "booklending",
      output_directory: "xcov_output"
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end